init_value=input('Enter the initial value');
final_value=input('Enter the final value');
n_values=input('Enter the initial value');
x=linspace(init_value,final_value,n_values);
y=logspace(init_value,final_value,n_values);
z=(init_value:final_value);
fprintf('LINSPACE\n');
disp(x);
fprintf('LOGSPACE\n');
disp(y);
fprintf('COLON\n');
disp(z);
